### PR TITLE
Filters: general comments

### PR DESCRIPTION
**Pull request by aaronArinder**
#### Problem
We need general comments on the structure of `filter.js`

#### Solution
Add some comments, shug

#### Notes
This closes out #4

### CODE REVIEW

**Comment by davidArinder** [comment]
Liz is correct, these PRs should be treated separately.

**Comment by aaronArinder** [comment]
@emcclosky, @davidArinder: fine

**Comment by aaronArinder** [comment]
but eternally I protest

**Comment by davidArinder** [comment]
Try your best not to be a little bitch, @aaronArinder.

**Pull request merged**
